modLoader="javafml"
loaderVersion="[${javafml_min},${javafml_max})"
issueTrackerURL="https://github.com/progwml6/ironshulkerboxes/issues"
license="GNU General Public License v3.0"

[[mods]]
    modId="ironshulkerbox"
    namespace="ironshulkerbox"
    version="${version}"
    displayName="Iron Shulker Boxes"
    authors="cpw, alexbegt, progwml6"
    description='''
New Shulker Boxes with larger sizes, with in-place upgrade items.
The feature shulker box is the crystal chest, which is transparent - some inventory contents are visible without opening the shulker box 
    '''
    displayURL="https://minecraft.curseforge.com/projects/iron-shulker-boxes"
    [[dependencies.ironshulkerbox]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version_min},${forge_version_max})"
        ordering="NONE"
        side="BOTH"
